### ISSUE TITLE
Change in behaviour with files from workspace folder

### ISSUE THREAD

**Issue by tazjin** [josh-project/josh#1155]
We're working on upgrading josh from a one year old version (https://github.com/josh-project/josh/commit/effe6290559136faba5591a115e56c2b30210329) to the latest one, and have run into an unexpected behaviour.

We have some workspaces that are defined in our monorepo, and "exported" to various other places. For example, there is a [`//views/tvix`](https://cs.tvl.fyi/depot/-/tree/views/tvix) workspace which constructs the exported view of our tvix project on Github: https://github.com/tvlfyi/tvix

When we upgrade to the latest josh, the resulting commit hashes from this workspace change. I poked around a bit and noticed that the files that were previously "pulled in" from the folder in which the workspace is located (e.g. this [buildkite.yml](https://cs.tvl.fyi/depot/-/blob/views/tvix/buildkite.yml) file) are now missing in the exported tree.

I read through many of the commits between then and now, but am not sure which one introduced this. Haven't had the time to bisect yet. Does this sound familiar, and is there a way to get the old behaviour back, so that we can continue the same commit history without force-pushing?

I've pushed a workspace filter with a new version of josh to the [hash-debug](https://github.com/tvlfyi/tvix/tree/hash-debug) branch, where it's visible that the contents of `default.nix` differ between it and the `canon` branch and the buildkite.yml file is missing.

**Comment by christian-schilling** [comment]
Sorry you are running into this...
We are quite careful to avoid this kind of behavior changes, but we needed to fix the behavior in cases where filters can "overlap", that is the same input path getting mapped to the same output path, to be able to have consistent behavior when reversing the filters.

What you did here is a bit strange because the last line in `workspace.josh` is `:/tvix`: A filter without any prefix, completely overlapping the actual workspace root. I have never seen that before ;)
But it is valid, so we have to deal with it...

That explains the difference in content of `default.nix`.

I can't explain the missing `buildkite.yml` yet so I will need to take a closer look at what is happening here.
The easy way out would be force push of course, but I'll check if we can do something else: In a similar (but certainly more complicated) way as the `:unsign` filter it might be possible the get to the same sha as before by somehow pre-filtering before applying the workspace.

**Comment by tazjin** [comment]
> What you did here is a bit strange because the last line in workspace.josh is :/tvix: A filter without any prefix, completely overlapping the actual workspace root. I have never seen that before ;)

Basically the idea of this is that the //views folder in our repository contains workspace definitions that "cherry-pick" other parts of the repository together, and enhance them with things like external-facing READMEs or CI definitions. This looks much more "lively" in the example of //views/kit (i.e. in the sibling folder to this one), as //tvix only needed some minor internal dependencies from the repo.

> In a similar (but certainly more complicated) way as the :unsign filter it might be possible the get to the same sha as before by somehow pre-filtering before applying the workspace.

If this arose because of a bugfix, then this is probably not worth it and we should just eat a force push (especially as we have no guarantees about the external copy of the repo right now). If it's doable with *existing* filters, that'd be nice, but if it needs new filters to be implemented then I'd vote for skipping it.

**Comment by christian-schilling** [comment]
> Basically the idea of this is that the //views folder in our repository contains workspace definitions that "cherry-pick" other parts of the repository together, and enhance them with things like external-facing READMEs or CI definitions. This looks much more "lively" in the example of //views/kit (i.e. in the sibling folder to this one), as //tvix only needed some minor internal dependencies from the repo.
Yes, that is what workspaces are meant to be used for. The problem here is just that workspaces always contain an implicit `:/<workspace root>` and with `:/tvix` now two canon folders are mapped to the same ws folders. That means even if you do get the right result for `read` access this will lead to ambiguity as soon as you try to push (it will work, but the result is probably not what you expect/want)
This problem is not present in the "kit" workspace. (It's sha should not have changed)


> If this arose because of a bugfix, then this is probably not worth it and we should just eat a force push (especially as we have no guarantees about the external copy of the repo right now). If it's doable with _existing_ filters, that'd be nice, but if it needs new filters to be implemented then I'd vote for skipping it.

The `default.nix` overlap should be fixable by filtering the not wanted one out first:
`::exclude[::tvix/default.nix]:workspace=views/tvix`

There might also be a solution for `buildkite.yml`.

If practical I would still go for the force push. But wait until the`buildkite.yml` absence is understood. In case there is another bug there.

**Comment by christian-schilling** [comment]
So I did some digging and it turned out this is actually a bug. The fix is in #1159 

With the fix applied the tvix workspace yields the same sha as before. So no force push will be necessary.

I would still recommend to change the workspace to not have an overlapping mapping for the root, for the reasons already described: It will not (cannot) work well if the backwards direction ever becomes important.

But I'm certainly glad you did it this way to expose this quite subtle bug. :)

**Comment by tazjin** [comment]
Great, confirmed that in combination with `:unsign` the latest commit yields the same hashes as before :)

Thanks so much!
