### ISSUE TITLE
Change behaviour on workspace empty mappings

### ISSUE THREAD

**Issue by LMG** [josh-project/josh#523]
Maybe it'd make sense to actually throw an error (and not a warning) on an empty mapping in a workspace.

Then we could add an option to allow people to clone a non-existent filter (-o ignore-unknown or something)

**Comment by christian-schilling** [comment]
We cannot have *any* fatal errors on the forward apply path because there would be no way to ever fix them due to git history being immutable.
After all, checking in a somehow broken workspace file is the same as checking in any other kind of broken config/code:
You need to define what "broken" means in your context and setup pre-submit checks (CI) to verify incoming changes.
