### ISSUE TITLE
Partially authenticated repositories

### ISSUE THREAD

**Issue by tazjin** [josh-project/josh#598]
We have a use-case where we run a publicly available josh instance at `code.tvl.fyi`, but would like to support authenticated use-cases to push back to the instance.

It seems that getting git to submit credentials without being asked for that by the remote is difficult (though my understanding of the code is that if they _were_ submitted, they would be used even if `require_auth` is unset).

My current understanding is that we'd have to change something in josh-proxy to send the correct `Unauthorized` response to prompt the credential flow. Happy to take a stab at this, any additional pointers welcome.

**Comment by tazjin** [comment]
Thinking more about this, it seems that the backend repository should *always* be the thing requesting authentication (i.e. its authentication-requesting responses should be threaded through, and `--require_auth` would become obsolete). Thoughts?

**Comment by christian-schilling** [comment]
You are right about the backend repo always having authority over authentication.
The only purpose of `--require_auth` is to make repo access a bit faster in scenarios where no-auth requests are not necessary.
The reason being that without that, josh will need one extra round trip to the backend server that will always fail, since the git client always tries unauthenticated first.
So it is purely a performance optimization to enable that option, you can run without it at a slight performance cost.

**Comment by christian-schilling** [comment]
I do feel there is something missing here though. But let's discuss that in private ;)

**Comment by tazjin** [comment]
> So it is purely a performance optimization to enable that option, you can run without it at a slight performance cost.

The problem is that I can't do any authenticated requests without it at all. Josh will return the remote's unauthorized response wrapped in an error, as far as I can tell.

**Comment by christian-schilling** [comment]
That is not how it is supposed to work. Will have to investigate what is wrong here.

**Comment by christian-schilling** [comment]
As of #747 this issue should be fixed if `--require-auth` is used.
I took (and adapted) the the solution from the the tvl fork, so thanks ;)
